---
swagger: '2.0'
info:
  version: v1
  title: KMD Logic Service API
paths:
  "/api/v1/ping":
    get:
      tags:
      - Ping
      operationId: ApiV1PingGet
      consumes: []
      produces:
      - application/json
      - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/PingResponse"
  "/api/v1/subscriptions/{subscriptionId}/sms/{smsMessageId}":
    get:
      tags:
      - Sms
      summary: Retrieve message delivery details by message Id
      operationId: ApiV1SubscriptionsBySubscriptionIdSmsBySmsMessageIdGet
      consumes: []
      produces:
      - application/json
      - text/json
      parameters:
      - name: subscriptionId
        in: path
        description: Consumer subscription Id
        required: true
        type: string
      - name: smsMessageId
        in: path
        description: A unique identifier for the SMS message
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/GetSmsResponse"
  "/api/v1/subscriptions/{subscriptionId}/sms":
    post:
      tags:
      - Sms
      summary: Sends a single SMS message.
      operationId: ApiV1SubscriptionsBySubscriptionIdSmsPost
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces:
      - application/json
      - text/json
      parameters:
      - name: subscriptionId
        in: path
        description: Consumer subscription Id
        required: true
        type: string
        format: uuid
      - name: request
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/SendSmsRequest"
      responses:
        '200':
          description: The SMS was queued for delivery
          schema:
            "$ref": "#/definitions/SendSmsResponse"
        '400':
          description: The body has missing/invalid values
          schema:
            type: object
            additionalProperties:
              uniqueItems: false
              type: array
              items:
                type: string
        '500':
          description: Internal server error
definitions:
  PingResponse:
    required:
    - version
    type: object
    properties:
      version:
        type: string
        readOnly: true
  GetSmsResponse:
    required:
    - smsMessageId
    - status
    type: object
    properties:
      smsMessageId:
        format: uuid
        description: A unique identifier for the SMS message.
        type: string
      status:
        "$ref": "#/definitions/SmsStatus"
        description: Status value which describes the current state of the message
  SmsStatus:
    enum:
    - sending
    - sent
    - failed
    type: string
  SendSmsRequest:
    required:
    - toPhoneNumber
    - body
    type: object
    properties:
      toPhoneNumber:
        description: 'Mobile phone number with country code ex: +919880266722'
        pattern: "^(\\+\\d{1,3}[- ]?)?\\d{10}$"
        type: string
      body:
        description: The text of the SMS message
        maxLength: 160
        minLength: 1
        type: string
      callbackUrl:
        description: "If provided, this URL endpoint will receive a POST request when
          there is any\r\nchange of the SMS message status (e.g. sending, sent and
          failed)."
        type: string
      providerConfigurationId:
        format: uuid
        description: "A unique identifier that represents the SMS provider and\r\nassociated
          configuration which this SMS message will be sent with."
        type: string
  SendSmsResponse:
    required:
    - smsMessageId
    type: object
    properties:
      smsMessageId:
        format: uuid
        description: A unique identifier for the SMS message.
        type: string
